# Configuration for Conditional Multi-Band UNet with Noise Conditioning

data:
  bin_dir: datasets
  bin_file: mel_spectrograms.h5
  data_key: mel_spectrograms
  lazy_load: true
  raw_dir: datasets/gin
  max_samples: 10
  sample_percentage: null
  variable_length: true
  
audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  fmin: 0
  fmax: 8000
  f0_min: 50
  f0_max: 600
  max_audio_length: 10.0

model:
  # Shared with original model
  time_frames: 864
  mel_bins: 80
  scale_factor: 1
  layer_count: 4
  encoder_channels: [16, 32, 64, 128]
  bottleneck_channels: 256
  decoder_channels: [64, 32, 16, 1]
  
  # Multi-band processing configuration
  num_freq_bands: 4
  band_overlap: 0.1
  
  # Variable length settings
  variable_length_mode: true
  
  nl_blocks:
    use_nl_blocks: true
    nl_in_bottleneck: true
    nl_mode: "embedded"
    nl_encoder_layers: [-1]
    nl_decoder_layers: [0]
    nl_reduction_ratio: 2
  
  dual_path:
    use_dual_path: true
    dual_path_encoder_layers: [-2, -1]
    dual_path_decoder_layers: [0, 1]

  low_freq_emphasis:
    use_lfe: true
    lfe_encoder_layers: "all"
    lfe_reduction_ratio: 8

  attention_head: 4
  loss_alpha: 0.8
  loss_beta: 0.2

# Conditioning-specific configuration
conditioning:
  # Embedding dimensions for phonemes and other features
  embedding_dim: 256
  hidden_dim: 256
  time_embed_dim: 128
  
  # Noise conditioning parameters
  noise_schedule: "linear"  # 'linear' or 'cosine'
  noise_steps: 1000
  min_beta: 0.0001
  max_beta: 0.02
  
  # Noise level ramp (in steps)
  # Set how many steps to transition from pure reconstruction to noise conditioning
  noise_ramp_steps: 10000
  
  # Minimum noise level to start with (0.0 = pure reconstruction)
  min_noise_level: 0.0

train:
  # Reduced batch size for the conditional model
  batch_size: 4
  accumulate_grad_batches: 2
  num_epochs: 1000
  learning_rate: 0.0005
  weight_decay: 0.0001
  lr_scheduler: reduce_on_plateau
  lr_patience: 10
  lr_factor: 0.8
  validation_split: 0.1
  log_interval: 100
  save_dir: logs/conditional_multiband_model
  num_workers: 4
  pin_memory: true
  precision: '16-mixed' #'32-true' '16-mixed'
  
validation:
  val_every_epoch: 2
  max_samples: 4
  
  logging:
    full_spectrum: true
    individual_bands: false
    merged_outputs: true
    error_analysis: false