# Model configuration for U-Net mel spectrogram reconstruction

# Data settings
data:
  bin_dir: datasets/gin/bin
  bin_file: gin.h5
  phone_map:
  raw_dir: datasets/gin
  
# Audio settings
audio:
  sample_rate: 22050  # Default sample rate for audio processing
  n_fft: 1024         # FFT size
  hop_length: 256     # Hop length for the STFT
  win_length: 1024    # Window length for the STFT
  n_mels: 80          # Number of mel bands
  fmin: 0             # Minimum frequency for mel spectrogram
  fmax: 8000          # Maximum frequency for mel spectrogram
  f0_min: 50          # Minimum F0 frequency in Hz
  f0_max: 600         # Maximum F0 frequency in Hz
  plots_dir: logs/preprocess/plots    # Directory to save visualization plots

# Model settings
model:
  # Input/output dimensions
  input_channels: 1
  output_channels: 1
  time_frames: 128
  mel_bins: 80
  
  # U-Net architecture
  encoder_channels: [16, 32, 64, 128]
  bottleneck_channels: 256
  decoder_channels: [64, 32, 16, 1]
  
  # Loss function weights
  loss_alpha: 0.8  # Weight for L1 loss
  loss_beta: 0.2   # Weight for Spectral Convergence loss

# Training settings
train:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  lr_scheduler: reduce_on_plateau
  lr_patience: 5
  lr_factor: 0.5
  validation_split: 0.1
  log_interval: 10
  save_interval: 10
  save_dir: runs/unet
  
  # Hardware
  num_workers: 4
  pin_memory: true
  
# Validation settings
validation:
  max_samples: 5  # Maximum number of samples to visualize